### PR TITLE
feat: add dark mode

### PR DESCRIPTION
**Pull request by SASUKE40**
Add dark mode
image
image

### CODE REVIEW

**Comment by Himself65** [comment]
Could u `yarn lint:fix`?

**Comment by SASUKE40** [comment]
I am fixing it, one second.

**Comment by SASUKE40** [comment]
Trouble in react life-cycle method migration, could you pls help fixing?

**Comment by SASUKE40** [comment]
The difference between `prettierrc` and `eslint` makes me confused.

**Comment by SASUKE40** [comment]
I have fixed it.

**Comment by Himself65** [comment]
thanks for your contribution!

**Pull request merged**
